### ISSUE TITLE
esllint estree parser is very out of date

### ISSUE THREAD

**Issue by paralin** [ipfs/eslint-config-ipfs#109]
The eslint estree parser is very out of date:

See https://github.com/ipfs/aegir/pull/1007

However due to dependency conflicts it may not be possible to upgrade until a new version is released here:

https://github.com/standard/eslint-config-standard-with-typescript/issues/831

**Comment by paralin** [comment]
Stalled out since May 10: https://github.com/standard/eslint-config-standard-with-typescript/issues/792

**Comment by achingbrain** [comment]
This will be fixed by https://github.com/ipfs/eslint-config-ipfs/pull/98

Closing in favour of that PR.
