### ISSUE TITLE
Change @typescript-eslint/return-await to `in-try-catch`?

### ISSUE THREAD

**Issue by achingbrain** [ipfs/eslint-config-ipfs#130]
The [default setting](https://github.com/standard/eslint-config-standard-with-typescript/blob/master/src/index.ts#L213) for `@typescript-eslint/return-await` is ['error', 'always'].

This disallows code like:

```ts
async function myAsyncFunction () {
  return someOtherAsyncFunction()
}
```

instead demanding:

```ts
async function myAsyncFunction () {
  return await someOtherAsyncFunction()
}
```

It doesn't seem to make any difference to the stack traces and we have other rules that catch floating promises so I'm not sure what value it adds, and it occasionally [raises](https://github.com/ipfs/helia/pull/17#discussion_r1095442723) some [eyebrows](https://github.com/libp2p/interop/pull/83#discussion_r1094064374).

The rule comes from standard but it's [not even clear](https://github.com/standard/eslint-config-standard-with-typescript/issues/417) that the standard maintainers are for this version of the rule.

It does have another mode which is `"in-try-catch"`, this disallows this sort of thing, demanding and `await` before the `return`, which seems a bit more useful, as it looks like the author might think any rejection would be caught which is not the case:

```ts
try {
  return someOtherAsyncFunction()
} catch (err) {
  // phew!
}
```

Shall we switch this rule to `"in-try-catch"`?

Cc @whizzzkid @SgtPooki

**Comment by SgtPooki** [comment]
@achingbrain I'm for this
