### ISSUE TITLE
Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc » eslint-config-ipfs#overrides[1] » ./ts': Cannot find module 'typescript'

### ISSUE THREAD

**Issue by mkg20001** [ipfs/eslint-config-ipfs#2]
typescript should be a dependency on the config as otherwise the rules don't work in standalone

**Comment by lidel** [comment]
cc @Gozala

**Comment by Gozala** [comment]
@mkg20001 readme attempts to explain this, you can use either

1. `{ "extends": "ipfs/js" }` if you don't care about typescript
2. If you use typescript it is expected that you have typescript in your setup that you supply.
3. You use `aegir` in which case typescript is supplied by it.

Do you have a use case where neither of those options fit

**Comment by achingbrain** [comment]
Closing as stale, please re-open if this is still a problem.
